### ISSUE TITLE
Some questions about the imputation loss

### ISSUE THREAD

**Issue by JaesikKim** [ssikjeong1/Deep_Recurrent_AD#1]
Hello. your paper looks very interesting.
I have two questions about the imputation loss.
 
According to equation (13) in the paper, "1-m_tilde", which is a masking matrix of random removal, is element-wise multiplicated to MAEs during a training phase. But, I cannot find the implementation code of that.
And, why did you use not the true mask "m", but the random mask "m_tilde" in the imputation loss? It will be great if you let me know the motivation for that.

Thanks!
Jaesik Kim

**Comment by ssikjeong1** [comment]
Thanks for your questions.
* You are able to find either "1-m_tilde" or "m_tilde" in the __setting.py__
(refer to _def sample_loader_, since line 135).
* Assuming your comment (if we just use the true mask "m"), we cannot evaluate the imputation performance because there are no true observations corresponding to the true mask "m". Therefore, we generated arbitrary missing observations in true observations for evaluating the performance, as illustrated figure below.
(Note that "m_tilde" includes the true mask "m".)
> (a) only use the true mask case, (b) use mask tilde case (generating arbitrary missing observations, blue x)

> Each red x, circle, green circle, blue x, and circle denotes true missing observation, imputed observation, true observation, arbitrary missing observation, and arbitrary imputed observation, respectively.

<img src="https://user-images.githubusercontent.com/31679505/146939841-f0fa2934-ee02-4b45-b0e1-650520bd962a.png" width="50%">

**Comment by JaesikKim** [comment]
Wow, very helpful. Thanks!
I have several more questions.

1) I don't still fully understand how you apply arbitrary missing in your code..
It seems ["Indices"](https://github.com/ssikjeong1/Deep_Recurrent_AD/blob/fc662c69d10725f7a3073da5116537e05c4969da/settings.py#L152) is making arbitrary missing, but it is not used further in the code.

2) In this [line](https://github.com/ssikjeong1/Deep_Recurrent_AD/blob/fc662c69d10725f7a3073da5116537e05c4969da/model.py#L142), why is it multiplying "m", not "1-m"?

3) Not sure about the definition of x_tilde_t (below equation (13)). 
I think $ x_tilde_t = x_t \odot **m_{x,t}** $ should be $ x_tilde_t = x_t \odot **m_tilde_{x,t}** $
Might be typo..? If not, why is it inconsistent?

3) The last question is to make sure of my understanding. In the experiments for tables 3,4,5, only your method is end-to-end. So, what I understood is that 
  a) For the competing method, first imputed missing values, then trained the model
  b) For your method, imputed the missing data and trained the model at the same time (by applying the arbitrary missing idea  here too)
Are those correct?

Sorry about too detailed or useless questions if wrong. But, I think your work is really interesting, so I'm enjoying learning your method.
Thanks!

**Comment by ssikjeong1** [comment]
Sorry for late replying to your questions.

I will upload them later.

Best regards,
